/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#f9f9ff',
        'surface-dim': '#d1daf4',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f3ff',
        'surface-container': '#e9edff',
        'surface-container-high': '#e1e8ff',
        'surface-container-highest': '#d9e2fc',
        'on-surface': '#121b2e',
        'on-surface-variant': '#434655',
        'inverse-surface': '#273044',
        'inverse-on-surface': '#edf0ff',
        outline: '#747686',
        'outline-variant': '#c4c5d7',
        'surface-tint': '#2151da',
        primary: '#0037b0',
        'on-primary': '#ffffff',
        'primary-container': '#1d4ed8',
        'on-primary-container': '#cad3ff',
        'inverse-primary': '#b7c4ff',
        secondary: '#5e4bc0',
        'on-secondary': '#ffffff',
        'secondary-container': '#9988ff',
        'on-secondary-container': '#2f1191',
        tertiary: '#7f2500',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#a73400',
        'on-tertiary-container': '#ffc9b7',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dce1ff',
        'primary-fixed-dim': '#b7c4ff',
        'on-primary-fixed': '#001551',
        'on-primary-fixed-variant': '#0039b5',
        'secondary-fixed': '#e5deff',
        'secondary-fixed-dim': '#c9bfff',
        'on-secondary-fixed': '#1a0063',
        'on-secondary-fixed-variant': '#4631a7',
        'tertiary-fixed': '#ffdbcf',
        'tertiary-fixed-dim': '#ffb59c',
        'on-tertiary-fixed': '#390c00',
        'on-tertiary-fixed-variant': '#832700',
        background: '#f9f9ff',
        'on-background': '#121b2e',
        'surface-variant': '#d9e2fc',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        gutter: '16px',
        'padding-spacious': '24px',
        'padding-compact': '8px',
        'container-margin': '24px',
        'padding-default': '16px',
      },
      fontFamily: {
        sans: ['IBM Plex Sans', 'sans-serif'],
        mono: ['SFMono-Regular', 'Consolas', 'monospace'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'mono-md': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '500' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
